# Workflow to build and deploys a Node.js application to an Azure App Service
# representing a production environment using reusable workflows.
#
# Triggered on pushing into main.

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:
  build:
    uses: gidavies/simplewebapp/.github/workflows/build.yml@main
    with:
      node_version: '16.x'

  deploy:
    uses: gidavies/simplewebapp/.github/workflows/deploy_to_azure.yml@main
    with:
      envName: 'Production'
      appServiceName: 'simplewebapp-gd'
    secrets:
      PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PROD }}
    needs: build