# Reusable workflow to deploy a Node app to an Azure App Service.
#
# Calling workflows include:
#   - The deployment workflow deploy_azure.yml
#   - The deployment if a label is added in the PR workflow deploy_on_label.yml

on:
  workflow_call:
    inputs:
      envName:
        required: true
        type: string
      appServiceName:
        required: true
        type: string
    secrets:
      PUBLISH_PROFILE:
        required: true

env:
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # Path to the web app project, defaults to the repository root

jobs:
  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.envName }}
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: node-app

    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp 
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ inputs.appServiceName }}
        publish-profile: ${{ secrets.PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
