# Deploy to a test Azure App Service instance when the deploy to test label is selected in a PR 

on:
  pull_request:
    types:
      - labeled

env:
  AZURE_WEBAPP_NAME: simple-app-gidavies-test    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root

permissions:
  contents: read

jobs:
  build:
    uses: gidavies/simple-app/.github/workflows/build.yml@main
    with:
      node_version: '16.x'

  deploy:
    if: github.event.label.name == 'deploy to test'
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Test'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: node-app

    - name: 'Deploy to Azure AppService Test instance'
      id: deploy-to-webapp 
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_TEST }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
