# Deploy to a test Azure App Service instance when the deploy to test label is selected in a PR 

on:
  pull_request:
    types:
      - labeled

jobs:
  build:
    uses: gidavies/simplewebapp/.github/workflows/build.yml@main
    with:
      node_version: '16.x'

   deploy:
    uses: gidavies/simplewebapp/.github/workflows/deploy_to_azure.yml@main
    with:
      envName: 'Test'
      appServiceName: 'simplewebapp-gd-test'
    secrets:
      PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_TEST }}
    needs: build
