# Workflow to build and deploys a Node.js application to an Azure App Service
# representing a test environment using reusable workflows.
#
# Triggered by applying a label in a PR.

on:
  pull_request:
    types:
      - labeled

jobs:
  build:
    uses: gidavies/simplewebapp/.github/workflows/build.yml@main
    with:
      node_version: '16.x'

  deploy:
    if: github.event.label.name == 'deploy to test'
    uses: gidavies/simplewebapp/.github/workflows/deploy_to_azure.yml@main
    with:
      envName: 'Test'
      appServiceName: 'simplewebapp-gd-test'
    secrets:
      PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_TEST }}
    needs: build